In [1]:
#Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [2]:
#Load dataset
url = "https://raw.githubusercontent.com/callxpert/datasets/master/Loan-applicant-details.csv"
names = ['Loan_ID','Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area','Loan_Status']
dataset = pd.read_csv(url, names=names)

In [3]:
dataset.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128,360,1,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66,360,1,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120,360,1,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141,360,1,Urban,Y
4,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267,360,1,Urban,Y
5,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95,360,1,Urban,Y
6,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158,360,0,Semiurban,N
7,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168,360,1,Urban,Y
8,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349,360,1,Semiurban,N
9,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70,360,1,Urban,Y
10,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200,360,1,Urban,Y
11,LP001029,Male,No,0,Graduate,No,1853,2840.0,114,360,1,Rural,N
12,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17,120,1,Urban,Y
13,LP001032,Male,No,0,Graduate,No,4950,0.0,125,360,1,Urban,Y
14,LP001036,Female,No,0,Graduate,No,3510,0.0,76,360,0,Urban,N
15,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133,360,1,Rural,N
16,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104,360,0,Urban,N
17,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315,360,1,Urban,Y
18,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116,360,0,Semiurban,N
19,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191,360,1,Semiurban,Y

In [4]:
# convert all our categorical variables into numeric by encoding the categories
from sklearn.preprocessing import LabelEncoder
var_mod = ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status']
le = LabelEncoder()
for i in var_mod:
    dataset[i] = le.fit_transform(dataset[i])

## Splitting the data

Our dataset has 480 records. We are going to use 80% of it for training the model and 20% of the records to evaluate our model

In [7]:
#we are only going to use the Income fields, loan amount, loan duration and credit history fields to train our model
array = dataset.values
X = X.astype('int')
Y = Y.astype('int')
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=7)

## Evaluating the model and training the Model

In [8]:
#Logistic Regression Model
model = LogisticRegression()
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

0.7708333333333334

In [9]:
#Decision tree
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

0.6458333333333334

In [10]:
#Random forest
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

0.7395833333333334

## Summary

The regression alogrithm works well in this instance, however, we could tweak the variables that we used for training the model to see if we could improve its accuracy.